<?php 
$usuarios = $data['usuarios'];
?>
<h2 class="sub-header"><?=$request['controller']?></h2>

<a href="/users/insert">Insert</a>
<div class="table-responsive">
<table class="table table-striped">
<?php foreach ($usuarios as $key => $usuario):?>
    <tr>
        <?php 
        $usuario = explode("|", $usuario); //Separar por pipes
        foreach($usuario as $key2 => $data):?>        
            <td><?=$data;?></td>
        <?php endforeach;?>
        <td>
            <a href="/users/update/id/<?=$key;?>">Update</a> | 
            <a href="/users/delete/id/<?=$key;?>">Delete</a>
        </td>     
    </tr>
<?php endforeach;?>
</table>
</div>